on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Build Electron app (staging)
    runs-on: ubuntu-latest
    env:
      CONFIG_FILE: config-staging.json
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Decrypt configuration
        run: ./server/deploy/decrypt-config.sh
        env:
          CONFIG_DECRYPT_PASSPHRASE: ${{ secrets.CONFIG_DECRYPT_PASSPHRASE }}
      - name: Build
        run: npm run package-all
        env:
          STAGING: 1
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Installer
          path: release/structure-*
          if-no-files-found: error
